eureka:
  client:
    service-url:
      defaultZone: http://eureka-primary:8881/eureka/,http://eureka-secondary:8882/eureka/
---
spring:
  profiles: ms-saleorder
words: Yo,Tu,El,Ella,Esto

---
spring:
  profiles: ms-shipping
words: corrió, sabía, tenía, vió, compró
---
spring:
  profiles: ms-invoicing
words: un,una,la
